# Generated by Django 2.1.7 on 2019-03-30 01:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('startDate', models.DateField(default=datetime.datetime.today)),
                ('endDate', models.DateField(default=datetime.datetime.today)),
                ('city', models.CharField(default='Bangalore', max_length=20)),
                ('Venue', models.TextField()),
                ('category', models.CharField(choices=[('CONF', 'Conference'), ('WORK', 'Workshops & Training'), ('FEST', 'College Fest'), ('SPRT', 'Sports Event'), ('ENTR', 'Entertainment Events'), ('REUN', 'Reunions'), ('TREK', 'Treks & Trips')], max_length=4)),
                ('ticketPrice', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='organiser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('company', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='participant',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='createdBy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='evite.organiser'),
        ),
    ]
