# Generated by Django 2.1.7 on 2019-03-30 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rsvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('ATT', 'Attending'), ('NAT', 'Not Attending'), ('NSU', 'Not Sure'), ('NDA', 'Not Filled')], max_length=3)),
                ('eventV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evite.event')),
            ],
        ),
    ]
