# Generated by Django 2.1.7 on 2019-03-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evite', '0002_rsvp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='organiser',
            name='image',
            field=models.ImageField(blank=True, upload_to='organisers'),
        ),
    ]
