# Generated by Django 2.1.7 on 2019-03-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evite', '0003_auto_20190330_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='organiser',
            name='attendee',
            field=models.ManyToManyField(to='evite.participant'),
        ),
    ]
