# Generated by Django 2.1.5 on 2019-03-30 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evite', '0005_auto_20190330_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evite.event')),
                ('participantV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evite.participant')),
            ],
        ),
    ]
